---
abstract: 'Interface to NewYorkTimes Movie Reviews API.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-MovieReviews-NYT
provides:
  WWW::MovieReviews::NYT:
    file: lib/WWW/MovieReviews/NYT.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
